[[Xorg_libpciaccess]]
arch = "armv7l"
git-tree-sha1 = "0aab0374da1841d215cf9d7483e17259e5695786"
libc = "glibc"
os = "linux"

    [[Xorg_libpciaccess.download]]
    sha256 = "6ff03a47599ee01025197d393ab8ccaecfd6a6d1d8cd131e24a14029d1ce4bf6"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libpciaccess_jll.jl/releases/download/Xorg_libpciaccess-v0.16.0+1/Xorg_libpciaccess.v0.16.0.armv7l-linux-gnueabihf.tar.gz"
[[Xorg_libpciaccess]]
arch = "i686"
git-tree-sha1 = "fe9a4b14e40710f0843df951034bb1000ff24415"
libc = "musl"
os = "linux"

    [[Xorg_libpciaccess.download]]
    sha256 = "e69387192d59425666ce1115dbb4d2ffec91bed0480d064dbfa459dbde0294c9"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libpciaccess_jll.jl/releases/download/Xorg_libpciaccess-v0.16.0+1/Xorg_libpciaccess.v0.16.0.i686-linux-musl.tar.gz"
[[Xorg_libpciaccess]]
arch = "aarch64"
git-tree-sha1 = "31bf0850217bed0f4f45c65e0ce6867a942562a2"
libc = "glibc"
os = "linux"

    [[Xorg_libpciaccess.download]]
    sha256 = "70c1ded555bb77ec91fae2ea5ba6109ee50b766ab1ab4d2f38b6562b0c35e0f8"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libpciaccess_jll.jl/releases/download/Xorg_libpciaccess-v0.16.0+1/Xorg_libpciaccess.v0.16.0.aarch64-linux-gnu.tar.gz"
[[Xorg_libpciaccess]]
arch = "armv7l"
git-tree-sha1 = "0d176e36e6f40b828941e0d618537a5a2faafec9"
libc = "musl"
os = "linux"

    [[Xorg_libpciaccess.download]]
    sha256 = "a35f01d1ff135cdab3a3394593ec58182f4229a302bafba48e3a2b3ab4040cac"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libpciaccess_jll.jl/releases/download/Xorg_libpciaccess-v0.16.0+1/Xorg_libpciaccess.v0.16.0.armv7l-linux-musleabihf.tar.gz"
[[Xorg_libpciaccess]]
arch = "aarch64"
git-tree-sha1 = "78b377972eaac142655c984d34f6695400998bc0"
libc = "musl"
os = "linux"

    [[Xorg_libpciaccess.download]]
    sha256 = "ba85556b5b684ad7b1bc6ca6c427fa6dc633c12d55b1db3009edc2b655ee49ba"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libpciaccess_jll.jl/releases/download/Xorg_libpciaccess-v0.16.0+1/Xorg_libpciaccess.v0.16.0.aarch64-linux-musl.tar.gz"
[[Xorg_libpciaccess]]
arch = "x86_64"
git-tree-sha1 = "6af7b31d6f9c4e56389cce1f7777d86d6298185e"
os = "freebsd"

    [[Xorg_libpciaccess.download]]
    sha256 = "0488095d21b96eb65865b273a530fbf5acad083e8c8549d6b5f677647778c237"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libpciaccess_jll.jl/releases/download/Xorg_libpciaccess-v0.16.0+1/Xorg_libpciaccess.v0.16.0.x86_64-unknown-freebsd11.1.tar.gz"
[[Xorg_libpciaccess]]
arch = "i686"
git-tree-sha1 = "a23395f02def105f489e6ac1ffe957d7fa938fb0"
libc = "glibc"
os = "linux"

    [[Xorg_libpciaccess.download]]
    sha256 = "3622bae48952738257295be0eb958f0d26923862f8d5422ae347435e7ec1f386"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libpciaccess_jll.jl/releases/download/Xorg_libpciaccess-v0.16.0+1/Xorg_libpciaccess.v0.16.0.i686-linux-gnu.tar.gz"
[[Xorg_libpciaccess]]
arch = "x86_64"
git-tree-sha1 = "60b1b07bb4803005743764fbc7a4513e17d80771"
libc = "musl"
os = "linux"

    [[Xorg_libpciaccess.download]]
    sha256 = "332a0b77715f2e01ffbb8d76b99372720dcfa6b74a164159806fc22a764514cc"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libpciaccess_jll.jl/releases/download/Xorg_libpciaccess-v0.16.0+1/Xorg_libpciaccess.v0.16.0.x86_64-linux-musl.tar.gz"
[[Xorg_libpciaccess]]
arch = "x86_64"
git-tree-sha1 = "fb5a719db10a52898b1a5454f71d3ec12f421557"
libc = "glibc"
os = "linux"

    [[Xorg_libpciaccess.download]]
    sha256 = "17901b92a4b8bfbc00b9e7483c9f45047f8c887371952901f3a1c26ce2a0480c"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libpciaccess_jll.jl/releases/download/Xorg_libpciaccess-v0.16.0+1/Xorg_libpciaccess.v0.16.0.x86_64-linux-gnu.tar.gz"
[[Xorg_libpciaccess]]
arch = "powerpc64le"
git-tree-sha1 = "b76cf116494cd7123f53cef8e8eb93fb82c44b82"
libc = "glibc"
os = "linux"

    [[Xorg_libpciaccess.download]]
    sha256 = "e6008463ee0afe4aaa6cad764e1867fc67a38746f33f80ed9d2041cb78dafee7"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libpciaccess_jll.jl/releases/download/Xorg_libpciaccess-v0.16.0+1/Xorg_libpciaccess.v0.16.0.powerpc64le-linux-gnu.tar.gz"
